# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        name: Format 2016.rs
        args: [--manifest-path, 2016.rs/Cargo.toml, --]
    -   id: clippy
        name: Run clippy on 2016.rs
        args: [
            --allow-dirty,
            --allow-staged,
            --manifest-path, 2016.rs/Cargo.toml,
            --all-targets,
            --fix,
            --,
            -W, "clippy::pedantic",
            -D, warnings
        ]

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        name: Format 2018.rs
        args: [--manifest-path, 2018.rs/Cargo.toml, --]
    -   id: clippy
        name: Run clippy on 2018.rs
        args: [
            --allow-dirty,
            --allow-staged,
            --manifest-path, 2018.rs/Cargo.toml,
            --all-targets,
            --fix,
            --,
            -W, "clippy::pedantic",
            -D, warnings
        ]

-   repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
    - id: black

-   repo: local
    hooks:
    - id: fantomas
      name: Fantomas (F# code formatter)
      entry: fantomas
      language: system
      files: \.(fs|fsx)$

# fantomas keeps changing the line endings to CRLF, that's why these are run last
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending
        args: ['--fix', 'lf']
