# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: [--manifest-path, 2016.rs/Cargo.toml, --]

-   repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
    - id: black

-   repo: local
    hooks:
    - id: fantomas
      name: Fantomas (F# code formatter)
      entry: fantomas
      language: system
      files: \.(fs|fsx)$

# fantomas keeps changing the line endings to CRLF, that's why these are run last
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending
        args: ['--fix', 'lf']
